#!/bin/bash

#Script: ArduInstall
#Autor: Antonio Mónaco
#Blog: www.peatonet.com
#E-mail: toni@peatonet.com
#Función: Instala, desinstala, y ejecuta Arduino IDE y Ardublock
#Versión: ArduInstall v1.0 (2015)
#Ejecutar: ./ArduInstall (Sin permisos de root ni sudo)

          #Establecemos las opciónes del menú
           OPCIONES="Instalar Desinstalar Ejecutar Salir"
           select opt in $OPCIONES; do

	     #Opción "Instalar del menú"
               if [ "$opt" = "Instalar" ]; then
                 #Instalamos Arduino IDE
                  sudo apt-get install -y arduino
                 #Descargamos la última versión de Ardublock
                  cd /tmp
                  sudo rm -rf ardu*
	          rm -rf ~/sketchbook
                  wget http://cloud.github.com/downloads/taweili/ardublock/ardublock-all.jar
                 #Creamos la jerarquía de directorios en sketchbook
		  mkdir ~/sketchbook
                  mkdir ~/sketchbook/tools
                  mkdir ~/sketchbook/tools/ArduBlockTool
                  mkdir ~/sketchbook/tools/ArduBlockTool/tool
                 #Movemos ArduBlockTool.jar a su carpeta
                  mv ardublock-all.jar ~/sketchbook/tools/ArduBlockTool/tool
		 #Ejecutamos Arduino IDE
		  arduino&
                exit

	     #Opción "Desinstalar del menú"
                elif [ "$opt" = "Desinstalar" ]; then
		 #Borramos ArduBlock
		  sudo rm -rf ~/sketchbook
		 #Desinstalamos Arduino IDE
		  sudo apt-get -y remove arduino
                exit

             #Opción "Ejecutar del menú"
                elif [ "$opt" = "Ejecutar" ]; then
		 #Ejecutamos Arduino IDE
	          arduino&
                exit

             #Opción "Salir del menú"
                elif [ "$opt" = "Salir" ]; then
                  echo done
                exit

	     #Opción erronea del menú
                else
                  clear
                  echo opción errónea
                fi
                done
